import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import {
  createRule,
  deleteRule,
  getRule,
  getSql,
} from '../../lib/db.js';

// Use a clearly throwaway pattern so if a test ever leaks a row, it's
// obvious where it came from.
const TEST_PATTERN = `/smoke-test/${randomUUID()}`;

// --- 1. createRule() inserts and returns the new row ------------------------
const created = await createRule({
  routePattern: TEST_PATTERN,
  clientKeyType: 'ip',
  limitCount: 10,
  windowSeconds: 60,
});
console.log('created ->', { id: created.id, createdAt: created.createdAt });

assert.match(
  created.id,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
  'id should be a UUID generated by Postgres'
);
assert.match(
  created.createdAt,
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/,
  'createdAt should be an ISO timestamp'
);
assert.equal(created.routePattern, TEST_PATTERN);
assert.equal(created.clientKeyType, 'ip');
assert.equal(created.limitCount, 10);
assert.equal(created.windowSeconds, 60);
assert.equal(created.strategy, 'sliding_window', 'should fall back to JS-side default');
assert.equal(created.enabled, true, 'should fall back to JS-side default');
console.log('createRule shape OK');

// --- 2. getRule(existingId) returns the same row ----------------------------
const fetched = await getRule(created.id);
assert.deepEqual(fetched, created, 'getRule should round-trip the created row');
console.log('getRule (hit) OK');

// --- 3. getRule(random UUID) returns null -----------------------------------
const missing = await getRule(randomUUID());
assert.equal(missing, null, 'getRule should return null for a non-existent id');
console.log('getRule (miss) OK');

// --- 4. deleteRule(existing) returns true -----------------------------------
const first = await deleteRule(created.id);
assert.equal(first, true, 'first delete should return true');
console.log('deleteRule (hit) OK');

// --- 5. deleteRule(same id again) returns false -----------------------------
const second = await deleteRule(created.id);
assert.equal(second, false, 'second delete should return false (already gone)');
console.log('deleteRule (miss) OK');

// --- 6. getRule after delete returns null -----------------------------------
const afterDelete = await getRule(created.id);
assert.equal(afterDelete, null, 'getRule should return null after deletion');
console.log('getRule after delete OK');

console.log('\nAll CRUD assertions passed. Table is back to its previous state.');

await getSql().end();
